### ISSUE TITLE
Roadmap 🔥

### ISSUE THREAD

**Issue by leobritob** [leobittencourt/finances-frontend#4]
### Clientes

- [ ] Criar tela de listagem de clientes
- [ ] Pesquisa de clientes
- [ ] Criar tela para adicionar novo cliente
- [ ] Criar tela para alterar cliente
- [ ] Exclusão de cliente

### Agenda

- [ ] Criar componente de agenda
- [ ] Criar tela de agendamentos
- [ ] Pesquisa de agendamentos
- [ ] Criar tela para adicionar novo agendamento
- [ ] Criar tela para alterar agendamento
- [ ] Exclusão de agendamento

### Produtos

- [ ] Criar tela de listagem de produtos
- [ ] Criar tela de estoque de produtos
- [ ] Pesquisa de produtos
- [ ] Criar tela para adicionar novo produto
- [ ] Criar tela para alterar produto
- [ ] Exclusão de produto
- [ ] Criar relatório de estoques de produtos
